[report.standard]
; Standard Device: Made up MKS transducer
std_manufacturer = MKS
std_model_number = 12345
std_serial_number = 12345
std_calibration_date = 7/13/2026
std_calibration_due_date = 7/13/2030
std_standard_accuracy = 50
std_accuracy_ratio = 50